### ISSUE TITLE
Failed to synthesis when the input sentence  contains coupled punctuations

### ISSUE THREAD

**Issue by JohnHerry** [Zz-ww/VITS-BigVGAN-SpanPSP-Chinese#6]
The punctuation processing may be not clean.
eg.  《科创板日报》1日讯,
         乌军将领:“最重磅战役”即将爆发 
will failed to synthesis.

**Comment by Zz-ww** [comment]
> The punctuation processing may be not clean. eg. 《科创板日报》1日讯, 乌军将领:“最重磅战役”即将爆发 will failed to synthesis.

我这里的中文前端处理是很简单的处理方式，对于很多符号，中英数字混合都不支持。你可以尝试调用一些成熟的tts中文前端，或者对prosody_txt.py的re.split('，|。|！|？|,|、|；|：|！', line.strip())进行一些标点符号的扩充。

**Comment by JohnHerry** [comment]
> > The punctuation processing may be not clean. eg. 《科创板日报》1日讯, 乌军将领:“最重磅战役”即将爆发 will failed to synthesis.
> 
> 我这里的中文前端处理是很简单的处理方式，对于很多符号，中英数字混合都不支持。你可以尝试调用一些成熟的tts中文前端，或者对prosody_txt.py的re.split('，|。|！|？|,|、|；|：|！', line.strip())进行一些标点符号的扩充。

感谢， 我觉得这个项目很棒的一个点，就是融入了韵律预测。我已经针对上述问题做了代码修正，不过感觉整体韵律还是会经常出问题。请问有哪些成熟的TTS中文前端项目可供参考的？ 感谢！

**Comment by Zz-ww** [comment]
> > > The punctuation processing may be not clean. eg. 《科创板日报》1日讯, 乌军将领:“最重磅战役”即将爆发 will failed to synthesis.
> > 
> > 
> > 我这里的中文前端处理是很简单的处理方式，对于很多符号，中英数字混合都不支持。你可以尝试调用一些成熟的tts中文前端，或者对prosody_txt.py的re.split('，|。|！|？|,|、|；|：|！', line.strip())进行一些标点符号的扩充。
> 
> 感谢， 我觉得这个项目很棒的一个点，就是融入了韵律预测。我已经针对上述问题做了代码修正，不过感觉整体韵律还是会经常出问题。请问有哪些成熟的TTS中文前端项目可供参考的？ 感谢！

我个人常用的中文前端是paddlespeech的frontend模块，如果需要进行韵律预测，需要对frontend的zh_frontend.py进行一些修改。

**Comment by JohnHerry** [comment]
好的，谢谢！
